workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      # groups:  # App Store Connect API key için (isteğe bağlı)
      #   - app_store_credentials
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.esnaftaucuz.app"
        APP_ID: "com.esnaftaucuz.app"
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web
        script: |
          npm run build
      - name: Add iOS platform if not exists
        script: |
          if [ ! -d "ios" ]; then
            echo "iOS platform not found, adding..."
            npx cap add ios
          else
            echo "iOS platform already exists"
          fi
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
          cd ../..
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Build iOS Archive
        script: |
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO || true
    artifacts:
      - build/ios/ipa/*.ipa
      - $CM_BUILD_DIR/build/*.xcarchive
      - $CM_BUILD_DIR/build/*.xcarchive/**/*
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false
      scripts:
        - name: Print build info
          script: |
            echo "Build completed!"
            echo "Bundle ID: $BUNDLE_ID"
            echo "Workspace: $XCODE_WORKSPACE"
            echo "Scheme: $XCODE_SCHEME"

