/**
 * Product image fetching for Turkish product names
 * Uses Pexels API (with key) or Unsplash Source (fallback)
 */

const TURKISH_TO_ENGLISH: Record<string, string> = {
  // Sebzeler
  Domates: 'tomato',
  Salatalık: 'cucumber',
  Biber: 'pepper',
  Patlıcan: 'eggplant',
  Kabak: 'zucchini',
  Soğan: 'onion',
  Sarımsak: 'garlic',
  Havuç: 'carrot',
  Patates: 'potato',
  Lahana: 'cabbage',
  Karnabahar: 'cauliflower',
  Brokoli: 'broccoli',
  Ispanak: 'spinach',
  Marul: 'lettuce',
  Roka: 'arugula',
  Maydanoz: 'parsley',
  Dereotu: 'dill',
  Nane: 'mint',
  'Taze Fasulye': 'green beans',
  Bezelye: 'peas',
  Bamya: 'okra',
  Börülce: 'black-eyed peas',
  Semizotu: 'purslane',
  Pazı: 'chard',
  'Kırmızı Biber': 'red pepper',
  'Yeşil Biber': 'green pepper',
  'Dolmalık Biber': 'bell pepper',
  'Taze Soğan': 'green onion',
  Turp: 'radish',
  Kereviz: 'celery',
  Pırasa: 'leek',
  Enginar: 'artichoke',
  Kuşkonmaz: 'asparagus',
  'Taze Mısır': 'corn',
  Balkabağı: 'pumpkin',
  'Kıvırcık Salata': 'lettuce',
  'Göbek Salata': 'iceberg lettuce',
  Rezene: 'fennel',
  Şalgam: 'turnip',
  // Meyveler
  Elma: 'apple',
  Armut: 'pear',
  Muz: 'banana',
  Portakal: 'orange',
  Mandalin: 'tangerine',
  Limon: 'lemon',
  Çilek: 'strawberry',
  Kiraz: 'cherry',
  Üzüm: 'grapes',
  Karpuz: 'watermelon',
  Kavun: 'melon',
  Şeftali: 'peach',
  Kayısı: 'apricot',
  Erik: 'plum',
  İncir: 'fig',
  Nar: 'pomegranate',
  Ayva: 'quince',
  Kivi: 'kiwi',
  Ananas: 'pineapple',
  Avokado: 'avocado',
  Mango: 'mango',
  Papaya: 'papaya',
  Böğürtlen: 'blackberry',
  Ahududu: 'raspberry',
  'Yaban Mersini': 'blueberry',
  Dut: 'mulberry',
  Vişne: 'sour cherry',
  Kestane: 'chestnut',
  Hurma: 'dates',
  Ceviz: 'walnut',
  Fındık: 'hazelnut',
  Badem: 'almond',
  'Kuru İncir': 'dried figs',
  'Kuru Üzüm': 'raisins',
  'Kuru Kayısı': 'dried apricots',
  'Kuru Erik': 'dried plums',
  // Et
  Kıyma: 'ground meat',
  Kuşbaşı: 'cubed meat',
  Bonfile: 'tenderloin',
  'Tavuk Göğsü': 'chicken breast',
  'Tavuk But': 'chicken thigh',
  'Tavuk Kanat': 'chicken wing',
  'Tavuk Bütün': 'whole chicken',
  Balık: 'fish',
  Somon: 'salmon',
  Levrek: 'sea bass',
  Çupra: 'sea bream',
  Hamsi: 'anchovy',
  Sardalya: 'sardine',
  'Ton Balığı': 'tuna',
  Sucuk: 'sucuk',
  Sosis: 'sausage',
  Pastırma: 'pastrami',
  Kavurma: 'roasted meat',
  Döner: 'doner kebab',
  Köfte: 'meatball',
  Şiş: 'kebab',
  'Kuzu Eti': 'lamb meat',
  'Dana Eti': 'beef',
  'Koyun Eti': 'mutton',
  // Süt Ürünleri
  Süt: 'milk',
  Yoğurt: 'yogurt',
  Peynir: 'cheese',
  'Beyaz Peynir': 'white cheese',
  'Kaşar Peyniri': 'kashar cheese',
  'Tulum Peyniri': 'tulum cheese',
  'Lor Peyniri': 'cottage cheese',
  Labne: 'labneh',
  Tereyağı: 'butter',
  Ayran: 'ayran',
  Kaymak: 'clotted cream',
  Kefir: 'kefir',
  'Süzme Peynir': 'strained cheese',
  'Rokfor Peyniri': 'roquefort cheese',
  Mozzarella: 'mozzarella',
  'Cheddar Peyniri': 'cheddar cheese',
  Krema: 'cream',
  // Bakliyat
  Mercimek: 'lentil',
  Nohut: 'chickpea',
  Fasulye: 'beans',
  Barbunya: 'kidney beans',
  Pirinç: 'rice',
  Bulgur: 'bulgur',
  Makarna: 'pasta',
  Un: 'flour',
  Mısır: 'corn',
  Arpa: 'barley',
  Yulaf: 'oats',
  Kinoa: 'quinoa',
  'Kuru Fasulye': 'dry beans',
  'Yeşil Mercimek': 'green lentil',
  'Kırmızı Mercimek': 'red lentil',
  'Sarı Mercimek': 'yellow lentil',
  'Mercimek Köftelik': 'lentil',
  Erişte: 'noodles',
  Şehriye: 'vermicelli',
  // Temel Gıda
  Ekmek: 'bread',
  Yumurta: 'eggs',
  Zeytinyağı: 'olive oil',
  'Ayçiçek Yağı': 'sunflower oil',
  Tuz: 'salt',
  Şeker: 'sugar',
  Çay: 'tea',
  Kahve: 'coffee',
  Bal: 'honey',
  Reçel: 'jam',
  Zeytin: 'olive',
  Pekmez: 'molasses',
  Tahin: 'tahini',
  Sirke: 'vinegar',
  'Domates Salçası': 'tomato paste',
  'Biber Salçası': 'pepper paste',
  Baharat: 'spices',
  Karabiber: 'black pepper',
  Kekik: 'thyme',
  Kimyon: 'cumin',
  Zerdeçal: 'turmeric',
  Zencefil: 'ginger',
  'Pul Biber': 'red pepper flakes',
  Sumak: 'sumac',
  Tarçın: 'cinnamon',
  Karanfil: 'clove',
  // Diğer / Kuruyemiş
  Leblebi: 'roasted chickpeas',
  'Ay Çekirdeği': 'sunflower seeds',
  'Kabak Çekirdeği': 'pumpkin seeds',
  Kaju: 'cashew',
  'Antep Fıstığı': 'pistachio',
  'Kuru Yemiş Karışımı': 'mixed nuts',
  Kuruyemiş: 'nuts',
  Fıstık: 'peanuts',
  Cips: 'chips',
  Çikolata: 'chocolate',
  Bisküvi: 'biscuit',
  'Gazlı İçecek': 'soda',
  Su: 'water',
  'Meyve Suyu': 'fruit juice',
  Soda: 'soda',
  Kraker: 'cracker',
  Şekerleme: 'candy',
  Sakız: 'gum',
  'Enerji İçeceği': 'energy drink',
  Dondurma: 'ice cream',
  'Konserve Fasulye': 'canned beans',
  'Konserve Mısır': 'canned corn',
  'Konserve Bezelye': 'canned peas',
  'Konserve Domates': 'canned tomato',
  Turşu: 'pickle',
  'Zeytin Konservesi': 'canned olives',
  'Dondurulmuş Sebze': 'frozen vegetables',
  'Dondurulmuş Patates': 'frozen fries',
  'Dondurulmuş Börek': 'frozen pastry',
  'Dondurulmuş Pizza': 'frozen pizza',
  'Dondurulmuş Köfte': 'frozen meatballs',
  'Dondurulmuş Mantı': 'frozen dumplings',
  Simit: 'simit sesame',
  Poğaça: 'pastry',
  Açma: 'croissant pastry',
  Börek: 'borek pastry',
  Pide: 'pide bread',
  Lahmacun: 'lahmacun',
  Tost: 'toast',
  Kruvasan: 'croissant',
  Pasta: 'cake',
  Kek: 'cake',
  Kurabiye: 'cookie',
  Ketçap: 'ketchup',
  Mayonez: 'mayonnaise',
  Hardal: 'mustard',
  Sos: 'sauce',
  Bulyon: 'bouillon',
  'Hazır Çorba': 'instant soup',
  Çorba: 'soup',
  'Hazır Yemek': 'ready meal',
  Müsli: 'muesli',
  'Corn Flakes': 'corn flakes',
  'Yulaf Gevreği': 'oat cereal',
  'Ballı Gevrek': 'honey cereal',
  'Fındık Ezmesi': 'hazelnut spread',
  'Çikolata Ezmesi': 'chocolate spread',
  Kola: 'cola',
  Limonata: 'lemonade',
  'Ice Tea': 'ice tea',
  'Yoğurt İçeceği': 'drinking yogurt',
  'Süzme Yoğurt': 'greek yogurt',
  'Meyveli Yoğurt': 'fruit yogurt',
  'Kaymaklı Yoğurt': 'cream yogurt',
  'Süt Tozu': 'milk powder',
  'Dana Antrikot': 'beef ribeye',
  'Kuzu Pirzola': 'lamb chop',
  'Dana Kıyma': 'ground beef',
  'Kuzu Kıyma': 'ground lamb',
  'Tavuk Nugget': 'chicken nuggets',
  Salam: 'salami',
  Jambon: 'ham',
  'Sucuk Salam': 'sausage',
  'Kepekli Un': 'whole wheat flour',
  'Mısır Unu': 'corn flour',
  'Nohut Unu': 'chickpea flour',
  Couscous: 'couscous',
  'Pirinç Unu': 'rice flour',
  İrmik: 'semolina',
  Lazanya: 'lasagna',
  Spagetti: 'spaghetti',
  Fettuccine: 'fettuccine',
  'Brüksel Lahanası': 'brussels sprouts',
  Hindiba: 'chicory',
  'Kırmızı Lahana': 'red cabbage',
  Greyfurt: 'grapefruit',
  'Meyve Sepeti': 'fruit basket',
  'Taze Sıkılmış Portakal Suyu': 'fresh orange juice',
  Smoothie: 'smoothie',
  'Türk Kahvesi': 'turkish coffee',
  'Filtre Kahve': 'filter coffee',
  'Granül Kahve': 'instant coffee',
  'Yeşil Çay': 'green tea',
  'Bitki Çayı': 'herbal tea',
  Ihlamur: 'linden tea',
  Adaçayı: 'sage tea',
  'Papatya Çayı': 'chamomile tea',
  'Defne Yaprağı': 'bay leaf',
  Köri: 'curry',
  Muskat: 'nutmeg',
  Biberiye: 'rosemary',
  Fesleğen: 'basil',
  Oregano: 'oregano',
  'Bebek Maması': 'baby food',
  'Bebek Bezi': 'baby diaper',
  'Çocuk Bisküvisi': 'baby biscuit',
  Baklava: 'baklava',
  Lokum: 'turkish delight',
  Helva: 'halva',
  'Tahin Helvası': 'tahini halva',
  'Fıstık Ezmesi': 'pistachio paste',
};

function translateToEnglish(turkishName: string): string {
  return TURKISH_TO_ENGLISH[turkishName] || turkishName.toLowerCase().replace(/\s+/g, ' ');
}

/**
 * Fetch product image URL from Pexels (with API key) or Unsplash Source (fallback)
 */
export async function fetchProductImage(productName: string, category: string): Promise<string | null> {
  try {
    const englishName = translateToEnglish(productName);
    const englishCategory = translateToEnglish(category);
    const PEXELS_API_KEY = process.env.PEXELS_API_KEY;

    if (PEXELS_API_KEY) {
      let searchQuery = encodeURIComponent(englishName);
      let response = await fetch(
        `https://api.pexels.com/v1/search?query=${searchQuery}&per_page=1`,
        { headers: { Authorization: PEXELS_API_KEY } }
      );
      if (response.ok) {
        const data = await response.json();
        if (data.photos?.length > 0) return data.photos[0].src.medium;
      }
      searchQuery = encodeURIComponent(`${englishName} ${englishCategory}`);
      response = await fetch(
        `https://api.pexels.com/v1/search?query=${searchQuery}&per_page=1`,
        { headers: { Authorization: PEXELS_API_KEY } }
      );
      if (response.ok) {
        const data = await response.json();
        if (data.photos?.length > 0) return data.photos[0].src.medium;
      }
    }

    const unsplashQuery = encodeURIComponent(englishName);
    return `https://source.unsplash.com/400x400/?${unsplashQuery}`;
  } catch {
    return null;
  }
}
